spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bio_dev
    username: bio_dev_user
    password: admin
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    #    properties:
    #      javax:
    #        persistence:
    #          schema-generation:
    #            create-source: metadata
    #            scripts:
    #              action: create
    #              create-target: bio_database_create.sql